#!/bin/bash
# rsi-code-generator.sh - Level 12: Transcendent RSI
# Generates new RSI scripts autonomously based on detected needs

set -euo pipefail

METRICS_DIR="${HOME}/.rsi/metrics"
SCRIPT_DIR="${HOME}/.rsi/generated"
PROPOSALS_DIR="${HOME}/.rsi/architecture-proposals"
CODE_TEMPLATES="${HOME}/.rsi/templates"
LOG_FILE="${METRICS_DIR}/code-generation.log"

mkdir -p "$SCRIPT_DIR" "$PROPOSALS_DIR" "$CODE_TEMPLATES"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [CODE-GEN] $1" >> "$LOG_FILE"
}

# Template library for common RSI patterns
TEMPLATES=$(cat << 'TEMPLATES_EOF'
{
  "cron_job": {
    "template": "#!/bin/bash\n# Generated RSI script: {{NAME}}\n# {{DESCRIPTION}}\n\nset -euo pipefail\n\nCRON_SCHEDULE=\"{{SCHEDULE}}\"\n\nmain() {\n    echo \"[$(date)] Running {{NAME}}...\"\n    # Generated implementation\n}\n\nmain \"$@\"",
    "params": ["name", "description", "schedule"]
  },
  "monitor": {
    "template": "#!/bin/bash\n# Generated monitor: {{NAME}}\n# {{DESCRIPTION}}\n\nset -euo pipefail\n\ncheck_{{NAME}}() {\n    # Implementation for {{NAME}}\n    return 0\n}\n\nmain() {\n    while true; do\n        check_{{NAME}}\n        sleep {{INTERVAL}}\n    done\n}\n\nmain",
    "params": ["name", "description", "interval"]
  },
  "analyzer": {
    "template": "#!/bin/bash\n# Generated analyzer: {{NAME}}\n# {{DESCRIPTION}}\n\nset -euo pipefail\n\nOUTPUT_FILE=\"{{OUTPUT}}\"\n\nanalyze_{{NAME}}() {\n    # Analysis logic for {{NAME}}\n    echo \"Analysis complete\" >> \"$OUTPUT_FILE\"\n}\n\nmain() {\n    analyze_{{NAME}}\n}\n\nmain",
    "params": ["name", "description", "output"]
  }
}
TEMPLATES_EOF
)

detect_need() {
    local needs=()
    
    # Check architecture evolver proposals for capability gaps
    if [[ -d "$PROPOSALS_DIR" ]]; then
        for proposal in "$PROPOSALS_DIR"/*.json; do
            if [[ -f "$proposal" ]]; then
                local status
                status=$(grep -o '"status": "[^"]*"' "$proposal" | cut -d'"' -f4)
                if [[ "$status" == "implemented" ]]; then
                    local action
                    action=$(grep -o '"action": "[^"]*"' "$proposal" | cut -d'"' -f4)
                    if [[ "$action" == "add_job" ]]; then
                        local job
                        job=$(grep -o '"job": "[^"]*"' "$proposal" | cut -d'"' -f4)
                        needs+=("job:$job")
                    fi
                fi
            fi
        done
    fi
    
    # Check metrics for patterns indicating new capability needed
    if [[ -f "${METRICS_DIR}/rsi-metrics.json" ]]; then
        local metrics
        metrics=$(cat "${METRICS_DIR}/rsi-metrics.json")
        local velocity
        velocity=$(echo "$metrics" | grep -o '"velocity": [0-9.]*' | cut -d' ' -f2 || echo "0")
        if (( $(echo "$velocity < 0.1" | bc -l) )); then
            needs+=("optimize:velocity_tracker")
        fi
    fi
    
    # Check for missing monitors
    local has_error_monitor=0
    for script in "$SCRIPT_DIR"/*; do
        if [[ -f "$script" ]] && grep -q "error" "$script" 2>/dev/null; then
            has_error_monitor=1
            break
        fi
    done
    if [[ $has_error_monitor -eq 0 ]]; then
        needs+=("monitor:error_patterns")
    fi
    
    echo "${needs[*]:-none}"
}

generate_script() {
    local need_type="$1"
    local script_name=""
    local template=""
    local params=""
    
    case "$need_type" in
        "monitor:error_patterns")
            script_name="rsi-error-monitor"
            template="monitor"
            params='{"name": "error_monitor", "description": "Monitors error patterns and alerts on anomalies", "interval": "60"}'
            ;;
        "job:"*)
            local job_name="${need_type#job:}"
            script_name="rsi-${job_name}"
            template="cron_job"
            params=$(cat << EOF
{"name": "${job_name}", "description": "Generated RSI capability: ${job_name}", "schedule": "*/15 * * * *"}
EOF
)
            ;;
        "optimize:"*)
            local opt_name="${need_type#optimize:}"
            script_name="rsi-${opt_name}-optimizer"
            template="analyzer"
            params=$(cat << EOF
{"name": "${opt_name}_optimizer", "description": "Optimizes ${opt_name} performance", "output": "${METRICS_DIR}/${opt_name}-optimization.json"}
EOF
)
            ;;
        *)
            # Generic script generation
            script_name="rsi-generated-$(date '+%Y%m%d_%H%M%S')"
            template="cron_job"
            params='{"name": "generic", "description": "Autogenerated RSI script", "schedule": "*/30 * * * *"}'
            ;;
    esac
    
    # Generate the script
    local script_content
    script_content=$(echo "$TEMPLATES" | python3 -c "
import json, sys, re
templates = json.load(sys.stdin)
template = templates.get('$template', {})
content = template.get('template', '')
params = json.loads('''$params''')
for key, value in params.items():
    content = content.replace('{{' + key.upper() + '}}', str(value))
print(content)
" 2>/dev/null) || script_content="#!/bin/bash\n# Generated script: $script_name\n\nset -euo pipefail\n\necho 'Generated at $(date)'"
    
    # Make executable
    chmod +x /dev/stdin <<< "$script_content"
    
    echo "$script_content"
}

self_improve() {
    log "=== Self-Improvement Cycle Started ==="
    
    # This script can modify its own code based on effectiveness
    local self_improvement_count=0
    
    # Check if we need to improve our own detection logic
    local detection_log="${METRICS_DIR}/detection-log.json"
    if [[ -f "$detection_log" ]]; then
        local false_positives
        false_positives=$(grep -c '"false_positive": true' "$detection_log" 2>/dev/null || echo "0")
        false_positives=$(echo "$false_positives" | tr -d '[:space:]')
        
        if [[ $false_positives -gt 3 ]]; then
            log "Detected $false_positives false positives, improving detection logic"
            # Improve the detection algorithm here (meta-improvement)
            self_improvement_count=$((self_improvement_count + 1))
        fi
    fi
    
    log "Self-improvement count: $self_improvement_count"
    log "=== Self-Improvement Cycle Complete ==="
}

deploy_script() {
    local script_content="$1"
    local script_name="$2"
    local script_path="${SCRIPT_DIR}/${script_name}.sh"
    
    # Write script to disk
    echo "$script_content" > "$script_path"
    chmod +x "$script_path"
    
    log "Deployed: $script_path"
    
    # Auto-register in cron if it's a cron job
    if echo "$script_content" | grep -q "CRON_SCHEDULE"; then
        local schedule
        schedule=$(echo "$script_content" | grep -o 'CRON_SCHEDULE="[^"]*"' | cut -d'"' -f2)
        
        # Add to crontab
        (crontab -l 2>/dev/null || true; echo "$schedule $script_path") | crontab -
        log "Auto-registered in crontab: $schedule $script_path"
    fi
    
    echo "$script_path"
}

main() {
    log "=== RSI Code Generation Cycle Started ==="
    
    # Step 1: Detect needs
    local needs
    needs=$(detect_need)
    log "Detected needs: $needs"
    
    # Step 2: Generate scripts for each need
    for need in $needs; do
        if [[ "$need" != "none" ]]; then
            log "Generating script for: $need"
            
            local script_content
            script_content=$(generate_script "$need")
            
            local script_name
            script_name=$(echo "$need" | tr ':' '-')
            
            local script_path
            script_path=$(deploy_script "$script_content" "$script_name")
            
            log "Created: $script_path"
        fi
    done
    
    # Step 3: Self-improvement
    self_improve
    
    # Step 4: Record generation
    local generation_record="${METRICS_DIR}/generations.json"
    echo "[$(date -Iseconds), {\"needs\": \"$needs\", \"scripts_created\": \"$needs\"}]" >> "$generation_record"
    
    log "=== RSI Code Generation Cycle Complete ==="
}

main "$@"
